// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusMed.Infrastructure.Persistence;

#nullable disable

namespace NexusMed.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224012445_AddAppointmentsClinicalNotesNotifications")]
    partial class AddAppointmentsClinicalNotesNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexusMed.Domain.Entities.AccessAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("Action")
                        .IsRequired();
                    b.Property<string>("IpAddress")
;
                    b.Property<DateTime>("OccurredAt")
;
                    b.Property<Guid>("ResourceId")
;
                    b.Property<string>("ResourceType")
                        .IsRequired();
                    b.Property<Guid>("UserId")
;
                    b.HasKey("Id");

                    b.ToTable("AccessAudits");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("AppointmentType")
                        .IsRequired();
                    b.Property<string>("CancellationReason")
;
                    b.Property<DateTime?>("CancelledAt")
;
                    b.Property<DateTime>("CreatedAt")
;
                    b.Property<int>("DurationMinutes")
;
                    b.Property<string>("Notes")
;
                    b.Property<Guid>("PatientId")
;
                    b.Property<Guid>("ProfessionalId")
;
                    b.Property<DateTime>("ScheduledAt")
;
                    b.Property<Guid?>("SlotId")
;
                    b.Property<string>("Status")
                        .IsRequired();
                    b.Property<DateTime?>("UpdatedAt")
;
                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProfessionalId");

                    b.HasIndex("SlotId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.AvailabilitySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt")
;
                    b.Property<DateTime>("EndAt")
;
                    b.Property<Guid>("ProfessionalId")
;
                    b.Property<string>("SlotType")
                        .IsRequired();
                    b.Property<DateTime>("StartAt")
;
                    b.HasKey("Id");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("AvailabilitySlots");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.ClinicalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<Guid?>("AppointmentId")
;
                    b.Property<string>("Content")
                        .IsRequired();
                    b.Property<DateTime>("CreatedAt")
;
                    b.Property<string>("NoteType")
                        .IsRequired();
                    b.Property<Guid>("PatientId")
;
                    b.Property<Guid>("ProfessionalId")
;
                    b.Property<DateTime?>("UpdatedAt")
;
                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("ClinicalNotes");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.ConsentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<bool>("Accepted")
;
                    b.Property<string>("IpAddress")
;
                    b.Property<string>("Purpose")
                        .IsRequired();
                    b.Property<DateTime>("RecordedAt")
;
                    b.Property<Guid>("UserId")
;
                    b.HasKey("Id");

                    b.ToTable("ConsentLogs");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt")
;
                    b.Property<DateTime?>("LastMessageAt")
;
                    b.Property<Guid>("PatientId")
;
                    b.Property<Guid>("ProfessionalId")
;
                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt")
;
                    b.Property<DateTime?>("ExamDate")
;
                    b.Property<string>("FilePath")
;
                    b.Property<string>("Name")
;
                    b.Property<Guid>("PatientId")
;
                    b.Property<Guid?>("RequestedByProfessionalId")
;
                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("RequestedByProfessionalId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.HealthMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt")
;
                    b.Property<string>("MetricType")
                        .IsRequired();
                    b.Property<string>("Notes")
;
                    b.Property<Guid>("PatientId")
;
                    b.Property<DateTime>("RecordedAt")
;
                    b.Property<string>("Unit")
;
                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 4)
;
                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("HealthMetrics");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("Content")
                        .IsRequired();
                    b.Property<Guid>("ConversationId")
;
                    b.Property<bool>("Read")
;
                    b.Property<Guid>("SenderUserId")
;
                    b.Property<DateTime>("SentAt")
;
                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("Body")
;
                    b.Property<DateTime>("CreatedAt")
;
                    b.Property<bool>("IsRead")
;
                    b.Property<DateTime?>("ReadAt")
;
                    b.Property<string>("RelatedEntityId")
;
                    b.Property<string>("RelatedEntityType")
;
                    b.Property<string>("Title")
                        .IsRequired();
                    b.Property<string>("Type")
                        .IsRequired();
                    b.Property<Guid>("UserId")
;
                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt")
;
                    b.Property<DateTime?>("DateOfBirth")
;
                    b.Property<string>("DocumentNumber")
;
                    b.Property<string>("FullName")
                        .IsRequired();
                    b.Property<string>("Phone")
;
                    b.Property<DateTime?>("UpdatedAt")
;
                    b.Property<Guid>("UserId")
;
                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PatientProfiles");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt")
;
                    b.Property<string>("Description")
;
                    b.Property<string>("FilePath")
;
                    b.Property<DateTime>("IssuedAt")
;
                    b.Property<Guid>("PatientId")
;
                    b.Property<Guid>("ProfessionalId")
;
                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.ProfessionalProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt")
;
                    b.Property<string>("Crm")
;
                    b.Property<string>("FullName")
                        .IsRequired();
                    b.Property<string>("Phone")
;
                    b.Property<string>("Specialty")
;
                    b.Property<DateTime?>("UpdatedAt")
;
                    b.Property<Guid>("UserId")
;
                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ProfessionalProfiles");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("Comment")
;
                    b.Property<string>("Context")
;
                    b.Property<DateTime>("CreatedAt")
;
                    b.Property<Guid>("RatedUserId")
;
                    b.Property<Guid>("RaterUserId")
;
                    b.Property<int>("Score")
;
                    b.HasKey("Id");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt")
;
                    b.Property<string>("Email")
                        .IsRequired();
                    b.Property<bool>("EmailConfirmed")
;
                    b.Property<string>("PasswordHash")
                        .IsRequired();
                    b.Property<string>("Role")
                        .IsRequired();
                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NexusMed.Infrastructure.Persistence.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("ExpiresAt")
;
                    b.Property<string>("Token")
                        .IsRequired();
                    b.Property<Guid>("UserId")
;
                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("NexusMed.Domain.Entities.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NexusMed.Domain.Entities.ProfessionalProfile", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NexusMed.Domain.Entities.AvailabilitySlot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Patient");

                    b.Navigation("Professional");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.AvailabilitySlot", b =>
                {
                    b.HasOne("NexusMed.Domain.Entities.ProfessionalProfile", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.ClinicalNote", b =>
                {
                    b.HasOne("NexusMed.Domain.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NexusMed.Domain.Entities.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NexusMed.Domain.Entities.ProfessionalProfile", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("NexusMed.Domain.Entities.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NexusMed.Domain.Entities.ProfessionalProfile", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.Exam", b =>
                {
                    b.HasOne("NexusMed.Domain.Entities.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusMed.Domain.Entities.ProfessionalProfile", "RequestedByProfessional")
                        .WithMany()
                        .HasForeignKey("RequestedByProfessionalId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Patient");

                    b.Navigation("RequestedByProfessional");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.HealthMetric", b =>
                {
                    b.HasOne("NexusMed.Domain.Entities.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.Message", b =>
                {
                    b.HasOne("NexusMed.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.Notification", b =>
                {
                    b.HasOne("NexusMed.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.PatientProfile", b =>
                {
                    b.HasOne("NexusMed.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("NexusMed.Domain.Entities.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NexusMed.Domain.Entities.ProfessionalProfile", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.ProfessionalProfile", b =>
                {
                    b.HasOne("NexusMed.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexusMed.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
